url_docker_registry_dockerhub = "https://hub.docker.com/r/kadoshita/http-echo"
url_source_repository         = "https://github/kadoshita/http-echo"
url_project_website           = "https://github/kadoshita/http-echo"
url_license                   = "https://github.com/kadoshita/http-echo/blob/main/LICENSE"
url_release_notes             = "https://github.com/kadoshita/http-echo/releases"
